server:
  port: 8080

spring:
  application:
    name: ji_xiao_yuan

  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ji_xiao_yuan?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: mYsQl9572580729

  # 正式环境(prod)、测试环境(dev)
  profiles:
    active: dev

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰功能
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL日志输出

  global-config:
    db-config:
      id-type: ASSIGN_ID # 使用雪花算法自动生成主键ID

ji_xiao_yuan:
  video_path: E:\code_exercise\Java\ji_xiao_yuan\src\main\resources\video # 视频存储路径